name: timetable

services:
    database:
        container_name: database
        image: postgres:17
        restart: unless-stopped
        expose:
            - 5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/data/
            - /tmp:/backups
        networks:
            - internal-network
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 512M
                reservations:
                    memory: 256M

    server:
        container_name: server
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile-server
        expose:
            - 3000
        depends_on:
            - database
        networks:
            - internal-network
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 1G
                reservations:
                    memory: 512M

    caddy:
        container_name: proxy
        build:
            context: .
            dockerfile: Dockerfile-caddy
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - internal-network
            - proxy-network
        depends_on:
            - server
        deploy:
            resources:
                limits:
                    cpus: "0.3"
                    memory: 256M
                reservations:
                    memory: 128M

volumes:
    postgres_data:
    caddy_data:
    caddy_config:

networks:
    internal-network:
        driver: bridge
    proxy-network:
        driver: bridge
