FROM caddy:2.9-builder AS builder

RUN xcaddy build --with github.com/mholt/caddy-ratelimit

FROM caddy:2.9

# Copy the built Caddy binary with the plugin
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
